/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'willie' at '9/4/16 10:21 PM' with Gradle 3.0
 *
 * @author willie, @date 9/4/16 10:21 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
